<template>
  <div style="text-align: start; margin-bottom: 100px; margin-left: 260px; margin-top: 100px">
    <h1>Information</h1>
    <h3># Out of the box working samples</h3>
    <hr>
    These samples are made for demonstration purposes only. They won't work out of the box if you copy paste them into your own website. This is because of how the docs are getting built. Some boilerplate code gets hidden. For a sample that can be copied and pasted and used directly you can check <span @click="''">the documents and samples page.</span>

    <h3># Autogenerated Charts</h3>
    <hr>
    The charts displayed on this page are automatically generated by predetermined settings. These features are not included with the library. For more information, see the Documents page.

    <h3># Codes block</h3>
    <hr>
    The samples have an code block. In these blocks, they are internally transformed to charts together by a plugin we use in the documentation. You can make some data and add options to them. Then you can call your variable in which you made the chart and do the logic.
  </div>
</template>

<script>
export default {
  name: "ChartWizardInformation"
}
</script>

<style scoped>
h3 {
  margin-top: 50px
}

body {
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;
}
</style>
