<template>
  <div style="text-align: start; margin-bottom: 100px; margin-left: 260px; margin-top: 100px">
    <h1>Information</h1>
    <h3># Out of the box working samples</h3>
    <hr>
    These samples are made for demonstration purposes only. They won't work out of the box if you copy paste them into your own website. This is because of how the docs are getting built. Some boilerplate code gets hidden. For a sample that can be copied and pasted and used directly you can check the usage page.

    <h3># Autogenerated data</h3>
    <hr>
    The data used in the samples is autogenerated using custom functions. These functions do not ship with the library, for more information about this you can check the utils page.

    <h3># Actions block</h3>
    <hr>
    The samples have an actions code block. These actions are not part of chart.js. They are internally transformed to separate buttons together with onClick listeners by a plugin we use in the documentation. To implement such actions yourself you can make some buttons and add onClick event listeners to them. Then in these event listeners you can call your variable in which you made the chart and do the logic that the button is supposed to do.
  </div>
</template>

<script>
export default {
  name: "ChartWizardInformation"
}
</script>

<style scoped>
h3 {
  margin-top: 50px
}

body {
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;
}
</style>